language: node_js
node_js:
  - "12.16.1"
jobs:
  include:
    - stage: install
      node_js: "12.16.1"
      before_script: cd packages/kvlt-konverter
      script: "npm install"
    - stage: test
      node_js: "12.16.1"
      before_script: cd packages/kvlt-konverter
      script: "npm test"
    - stage: release
      if: tag IS present
      node_js: "12.16.1"
      script: echo "Deploying to npm ..."
      before_deploy: cd packages/kvlt-konverter
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
