language: node_js
node_js:
  - '12.16.1'

before_install: cd packages/kvlt-konverter

jobs:
  include:
    - stage: npm release
      node_js: '12.16.1'
      script: echo 'Deploying to npm ...'
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: deploy-npm-release
