language: node_js
node_js:
  - "12.16.1"
jobs:
  include:
    - stage: test kvlt-konverter npm package
      node_js: "12.16.1"
      before_script: cd packages/kvlt-konverter && npm install
      script: "npm test"
    - stage: release kvlt-konverter npm package
      node_js: "12.16.1"
      before_script: cd packages/kvlt-konverter && npm install
      script: ./release.sh "$NPM_EMAIL" "$NPM_TOKEN"
    - stage: release kvlt-discord-bot docker image
      before_script: cd packages/kvlt-discord-bot
      script: ./release.sh "$DOCKER_USERNAME" "$DOCKER_PASSWORD"
    - stage: release kvlt-telegram-bot docker image
      before_script: cd packages/kvlt-telegram-bot
      script: ./release.sh "$DOCKER_USERNAME" "$DOCKER_PASSWORD"
    - stage: deploy to aws
      before_script: cd aws/kvlt-bots && ./install.sh
      script: ./release.sh "$DOCKER_USERNAME" "$DOCKER_PASSWORD"
